// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD59hdiUtr6QA88POxJf3egfjhve5AsQfM',
    appId: '1:341021968841:web:5d833659cdfca263534018',
    messagingSenderId: '341021968841',
    projectId: 'neighbour-share-app',
    authDomain: 'neighbour-share-app.firebaseapp.com',
    storageBucket: 'neighbour-share-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt9AVskehfiUHlz9cbMJR4zdubi9ZUguQ',
    appId: '1:341021968841:android:84e2326ec15712c5534018',
    messagingSenderId: '341021968841',
    projectId: 'neighbour-share-app',
    storageBucket: 'neighbour-share-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxEf7e-aeMsHQOScFuFPSGwjGg1vUiYC4',
    appId: '1:341021968841:ios:35ffdda3556283d9534018',
    messagingSenderId: '341021968841',
    projectId: 'neighbour-share-app',
    storageBucket: 'neighbour-share-app.firebasestorage.app',
    iosBundleId: 'com.example.neighborShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxEf7e-aeMsHQOScFuFPSGwjGg1vUiYC4',
    appId: '1:341021968841:ios:35ffdda3556283d9534018',
    messagingSenderId: '341021968841',
    projectId: 'neighbour-share-app',
    storageBucket: 'neighbour-share-app.firebasestorage.app',
    iosBundleId: 'com.example.neighborShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD59hdiUtr6QA88POxJf3egfjhve5AsQfM',
    appId: '1:341021968841:web:f60dac7175869938534018',
    messagingSenderId: '341021968841',
    projectId: 'neighbour-share-app',
    authDomain: 'neighbour-share-app.firebaseapp.com',
    storageBucket: 'neighbour-share-app.firebasestorage.app',
  );
}
